version: '3'
services:
  db:
    container_name: lamarbooru-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${FILES_DIRECTORY}:/files
      - ${THUMBNAILS_DIRECTORY}:/thumbnails
    depends_on:
      - db
    ports:
        - "6969:6969"
    environment:
      - NODE_ENV=production
      - PORT=6969
      - DATABASE_URL=postgresql://postgres:postgres@lamarbooru-postgres:5432/postgres?schema=lamarbooru
      - FILES_DIRECTORY=/files
      - THUMBNAILS_DIRECTORY=/thumbnails
      - DELETE_MISPLACED_FILES=false
